# 《数字图像处理》

2025年春，中南大学

## 基于Python的编程环境与平台

### Python的安装

从www.python.org下载安装程序，最新版本是3.14，但常用的是3.09-3.11

也可从其他python发布包，比如http://winpython.github.io/ 下载。解压缩后即可使用。

## 第三方库的安装

pip install 库名

pip install --upgrade 库名

pip uninstall 库名

查“pip 国内源”可以找到更快的更新来源

#### Python语言入门简介

Python是一种解释执行的语言，执行速度比C/C++慢的多，但语法更简洁易用，目前广泛应用于数据分析、人工智能、网络后端开发等领域。针对其执行速度慢的缺点，核心计算代码往往采用C/C++实现，然后通过接口的方式让Python调用。这样既保证了效率，也兼顾了易用性。

因为它是解释执行的语言，所以输入指令按回车后，指令会立即被执行。比如你输入：

In [43]:
1+2

3

当然也可以用变量来保存不同类型的数据，而且它不需要实现声明变量类型，它是根据你的具体赋值来猜测变量的类型。比如：

In [44]:
a = 1
type(a)

int

In [45]:
a = 1.4
type(a)

float

In [46]:
a = 'OK'
type(a)

str

你可以用列表来保存数组，不需要实现指定列表长度，可以随时增删数据，而且同一个列表中可以存放不同类型的元素。比如：

In [47]:
lst = []
type(lst)

list

In [48]:
lst.append(a)
lst

['OK']

In [49]:
len(lst)

1

In [50]:
del lst[0]  #  注意它是以0开始索引元素的，而且是用方括号来访问特定序号的元素
len(lst)

0

In [51]:
lst = [2, 3]
print(lst)  # print命令可以打印常见类型变量的内容
lst.remove(2) # 请观察.remove方法与前面的del命令有何不同？
print(lst)

[2, 3]
[3]


In [52]:
lst = [2, 'OK'] #列表中可以保存不同类型的元素
print(lst)

[2, 'OK']


对于数字图像而言，需要保存的数据量往往是百万级别起步的，如果用list类型则效率太低。而***Numpy***模块为Python语言提供了一种高效的数值矩阵保存和运算功能。它的底层是用C语言实现的，但其语法则保持了Python的简洁性，并且与流行的Matlab语言相似。因此Numpy几乎被广泛运用于所有面向科学计算的Python应用中。

In [53]:
#首先导入Numpy模块，这很像C语言中的include语句
import numpy

In [54]:
#为了便于更简洁地调用numpy的功能，往往在导入该模块时给他一个别名
import numpy as np

导入后，就可以调用Numpy中的各项功能了。首先，创建一个2行3列的矩阵。

In [55]:
mat_1 = np.zeros((2,3),dtype=np.float32)
print(mat_1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [56]:
mat_1.dtype

dtype('float32')

由于调用的时zeros函数，因此生成的矩阵的元素初值都是0.类似的函数还有ones，可以生成初值为1的矩阵。

In [57]:
#打印该矩阵第1行第1列的值
print(mat_1[0,0])

0.0


与list列表不同，每个numpy矩阵中的值必须都是同样的数据类型。比如这个刚生成的矩阵，我们可以查看任意两个元素的类型。

In [58]:
print(type(mat_1[0,0]), type(mat_1[0,1]))

<class 'numpy.float32'> <class 'numpy.float32'>


In [59]:
mat_1[0,1] = 1
print(mat_1)

[[0. 1. 0.]
 [0. 0. 0.]]


看来，如非特别指定，默认的矩阵元素是64位浮点数类型的。我们可以在创建时，指定其类型。

In [60]:
mat_2 = np.ones((3,4), dtype='uint8')
print(mat_2[0,0], type(mat_2[0,0]))

1 <class 'numpy.uint8'>


这个刚创建的'uint8'类型的矩阵，就是我们在后面最常看到的图像初始数值类型。因为每个像素默认每个通道用一个字节，即无符号的8位(unsigned int 8bits，简写就是uint8)来表示。

In [61]:
mat_3 = mat_2.astype(np.float32)

上面这个新创建的矩阵mat_3其内容与mat_2一样，但元素的数值类型被转换为32位浮点数。这也是将来很常用到的转换，因为我们要对图像内容进行分析和计算，初始的无符号的8位是不够用的。

In [62]:
print(mat_3)
print(type(mat_3[0,0]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.float32'>


numpy矩阵可以方便的进行各种数值运算，比如矩阵与一个标量相加。

In [63]:
mat_4 = mat_3 + 1
print(mat_4)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


还可以将两个矩阵相加，点乘等

In [64]:
mat_5 = mat_3 + mat_4
print(mat_5)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [65]:
mat_6 = mat_3 * mat_4
print(mat_6)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


改变某个元素的值

In [66]:
mat_6[2,2] = 7
print(mat_6)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 7. 2.]]


按条件更改某些元素的值

In [67]:
mat_6[mat_6<7] = 0
print(mat_6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 7. 0.]]


In [68]:
mat_6<7

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

获取矩阵的某一行

In [69]:
row1 = mat_6[2, :]
print(row1)

[0. 0. 7. 0.]


获取矩阵的某一列

In [70]:
col1 = mat_6[:, 2]
print(col1)

[0. 0. 7.]


获取矩阵的某一个区域

In [71]:
region1 = mat_6[1:, 1:3]
print(region1)

[[0. 0.]
 [0. 7.]]


***注意:**在上面对region1的赋值代码中，"1:"表示获取从第2行（因为python的数组也是从0开始编号的）到最后一行，"1:3"表示获取从第2列到第3列的内容。

"1:3"表示一个数值范围，从1到3但不包括3。这是python的语法约定，与下面的range函数是相似的。

前面的示例已经演示了顺序执行的代码，注意：**是不需要“；”**结束符的

**下面来演示循环的语法**

In [78]:
for i in range(3):
    print(i)
    print('OK')

0
1
2


其中range函数返回一个整数序列，请看：

In [73]:
list(range(3)) 

[0, 1, 2]

所以上面的循环代码中，i分别取0,1,2三个值。如果你想让循环变量i取不同的值域，可以用这样的语法：

In [74]:
list(range(1,4))#注意：值域的上限比第二个参数小1.

[1, 2, 3]

In [75]:
list(range(1,6,2)) #还可以通过添加第3个参数来指定元素间的步长

[1, 3, 5]

**特别容易出错的是：**
- 忘记写for语句所在行结尾的冒号
- 忘记给循环体缩进。由于Python没有语句的开始和结束符“{}”，所以它是通过缩进来识别for语句的循环体代码范围的。一般用Tab键缩进，或者统一缩进固定长度的字符。

**最后来演示分支语句的语法**

In [76]:
a = 0
if a > 0:
print('a>0')
elif a==0:
    print('a==0')
else:
    print('a<0')

IndentationError: expected an indented block after 'if' statement on line 2 (2046190172.py, line 3)

通过上面的if语句示范可见，python的分支语句与其他语言类似，只是个别标识符不一样，比如elif；此外，每一个分支条件语句都要跟一个冒号。而且是通过缩进的方式来划定分支语句的范围的。

#### 2.3 Python语言的其他关键语法

有了上面的基础，大家就不难调研Python的其他关键语法了：
- 函数的定义和调用方法
- 面向对象编程方法
- 模块(module)的定义和使用方法